### ISSUE TITLE
Syslog alerts on Linksys EA8300

### ISSUE THREAD

**Issue by sleeplezz1** [NoTengoBattery/openwrt#10]
Got this in my syslog: 

> Tue Jan 26 18:07:52 2021 kern.err kernel: [    0.776539] bam-dma-engine 8e04000.dma: num-channels unspecified in dt
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    0.776737] bam-dma-engine 8e04000.dma: num-ees unspecified in dt
> 
> 
> 
> Tue Jan 26 18:07:52 2021 kern.alert kernel: [    1.724769] mtdsplit: no squashfs found in "rootfs"
> 
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    2.509735] zswap: default zpool zbud not available
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    2.513499] zswap: pool creation failed
> 
> 
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.256349] dwc3-qcom 8af8800.usb3: IRQ hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.256539] dwc3-qcom 8af8800.usb3: IRQ dp_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.261153] dwc3-qcom 8af8800.usb3: IRQ dm_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.269105] dwc3-qcom 8af8800.usb3: IRQ ss_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.274468] dwc3-qcom 60f8800.usb2: IRQ hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.278680] dwc3-qcom 60f8800.usb2: IRQ dp_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.284287] dwc3-qcom 60f8800.usb2: IRQ dm_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.289957] dwc3-qcom 60f8800.usb2: IRQ ss_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.297757] dwc3 8a00000.dwc3: Failed to get clk 'ref': -2
> Tue Jan 26 18:07:52 2021 kern.err kernel: [    5.413258] dwc3 6000000.dwc3: Failed to get clk 'ref': -2
> 
> 
> Tue Jan 26 18:08:00 2021 authpriv.warn dropbear[3504]: Failed listening on '22': Error listening: Address not available
> Tue Jan 26 18:08:00 2021 authpriv.info dropbear[3504]: Not backgrounding
> 
> Tue Jan 26 18:09:01 2021 daemon.warn odhcpd[2680]: A default route is present but there is no public prefix on lan thus we 
> don't announce a default route!
> Tue Jan 26 18:09:01 2021 kern.warn kernel: [   60.296716] ath10k_ahb a000000.wifi: Invalid peer id 6 or peer stats buffer, peer: 00000000`  sta: 00000000

Also got this:

> Tue Jan 26 18:07:54 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!

Thought dnsmasq is uninstalled ? 

Also some kernel errors in kernel log :

> [  136.455906] ath10k_ahb a000000.wifi: wmi: fixing invalid VHT TX rate code 0xff
> [  308.443481] ath10k_ahb a000000.wifi: htt tx: fixing invalid VHT TX rate code 0xff

**Comment by NoTengoBattery** [comment]
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 0.776539] bam-dma-engine 8e04000.dma: num-channels unspecified in dt
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 0.776737] bam-dma-engine 8e04000.dma: num-ees unspecified in dt

These logs are because the device tree needs to be refactored. It tells you that the chip supported features that are not enabled [because your manufacturer did not physically implement them]. They are harmless. I will not refactor these files, because they are really hard to maintain.

> Tue Jan 26 18:07:52 2021 kern.alert kernel: [ 1.724769] mtdsplit: no squashfs found in "rootfs"

This is because the rootfs partition is not ready at that moment. It will be ready later when needed; otherwise, the device will not boot at all. It is harmless.

> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 2.509735] zswap: default zpool zbud not available
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 2.513499] zswap: pool creation failed

To reduce the kernel's image size, `zbud`, `z3fold`, and `zsmalloc` are installed as modules. At that point [because of the same reason as the message above], they are not yet available, but they will. It is harmless.

> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.256349] dwc3-qcom 8af8800.usb3: IRQ hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.256539] dwc3-qcom 8af8800.usb3: IRQ dp_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.261153] dwc3-qcom 8af8800.usb3: IRQ dm_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.269105] dwc3-qcom 8af8800.usb3: IRQ ss_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.274468] dwc3-qcom 60f8800.usb2: IRQ hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.278680] dwc3-qcom 60f8800.usb2: IRQ dp_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.284287] dwc3-qcom 60f8800.usb2: IRQ dm_hs_phy_irq not found
> Tue Jan 26 18:07:52 2021 kern.err kernel: [ 5.289957] dwc3-qcom 60f8800.usb2: IRQ ss_phy_irq not found

Same reason as the first message.

> Tue Jan 26 18:08:00 2021 authpriv.warn dropbear[3504]: Failed listening on '22': Error listening: Address not available
> Tue Jan 26 18:08:00 2021 authpriv.info dropbear[3504]: Not backgrounding

You can configure `dropbear` here: http://dallas/cgi-bin/luci/admin/system/admin/dropbear

> Tue Jan 26 18:09:01 2021 daemon.warn odhcpd[2680]: A default route is present but there is no public prefix on lan thus we
> don't announce a default route!

This is due to your particular ISP set up for IPv6, they are harmless in general.

> Tue Jan 26 18:09:01 2021 kern.warn kernel: [ 60.296716] ath10k_ahb a000000.wifi: Invalid peer id 6 or peer stats buffer, peer: 00000000` sta: 00000000
> [ 136.455906] ath10k_ahb a000000.wifi: wmi: fixing invalid VHT TX rate code 0xff
> [ 308.443481] ath10k_ahb a000000.wifi: htt tx: fixing invalid VHT TX rate code 0xff

This is the ATH10K wireless driver. They are harmless in general. If you experience some particular issue that you can pinpoint to this particular message [because they coincide in time], you can report a bug to the ath10k mailing list: http://lists.infradead.org/mailman/listinfo/ath10k

> Thought dnsmasq is uninstalled?

I guess is not uninstalled, then. You can disable it from running at all, installed or not, by setting up the DNS port to 0 here: http://dallas/cgi-bin/luci/admin/network/dhcp
Remember that a working DNS server is essential for the network to work correctly.

---
All of these messages are harmless, in general, and unless you can correlate them to a particular issue. The most problematic, if they even are, are the ones related to ATH10K, but in that case, the ATH10K developers will be glad to have a proper bug report.

In the end, this is not more than an OpenWrt snapshot with tweaks and fixes, and with some programs preinstalled. I do not modify the source code for `dnsmasq` or `dropbear`, for example.

 If you are experiencing a particular problem with something other than the kernel (such as boot loops, lockups, or random reboots) or the `compressed-memory` app, you want to discuss the problem with the maintainer in the OpenWrt repository or in the forums.

Thanks for your comments. I am offline in the OpenWrt forum at this moment for studying reasons, but I am always aware of GitHub. Do not hesitate to ask any other question you may have related to this project (even if I am not the maintainer of a package, I can help if I know how to use or configure it).
