### ISSUE TITLE
Slow resolving on MR8300 (2.10)

### ISSUE THREAD

**Issue by parkerlreed** [NoTengoBattery/openwrt#11]
OpenWRT snapshot runs great on the device. I wanted to try out this fork and while it flashes and boots fine, resolving seems to take a hit.

Sites like YouTube for example take longer to load and a bunch of the elements take even longer to pop in. 

Other sites seemingly load fine. Is this possibly an issue with unbound?

I tried this firmware a week ago and saw the same behavior but chalked it up to possible Internet issues. 

Video example https://streamable.com/lpx78g

**Comment by parkerlreed** [comment]
Tried disabling adblock and the DNS forward to unbound in the router settings and changed the DNS on the computer to 1.1.1.1. Seems to still be weird on YouTube.

**Comment by parkerlreed** [comment]
Performed a settings reset from NoTengo and it appears to be working for the time being... Back on the routers DNS and unbound. I'll update if it shows up again.

**Comment by NoTengoBattery** [comment]
Hello,

I use Unbound by default because of the DoT to Quad9. dnsmasq does not allow the usage of DoT. dnsmasq and Unbound are chained because dnsmasq is superior to Unbound to resolve local names (mostly because it is also called the IPv4 DHCP server).

Because of this, the cache for dnsmasq is disabled since Unbound handles the caching. Unbound is known to be slower than dnsmasq sometimes, especially when doing TLS. I would recommend you remove the forwarding to Unbound, use a fast upstream DNS server and stop/disable the Unbound service.

To re-enable the dnsmasq cache, go here: http://dallas/cgi-bin/luci/admin/network/dhcp, uncheck the `No negative cache` option and change the `Size of DNS query cache` to something suitable for your needs.

**Comment by parkerlreed** [comment]
Thanks. Great to have in case this crops back up. Seems good for the time being on the default setup. Thanks a lot for this fork!
