### ISSUE TITLE
can't install sqm

### ISSUE THREAD

**Issue by devgar12** [NoTengoBattery/openwrt#7]
I can't install the luci-app-sqm package because it says I have the wrong kernel version. It requires a more updated version. I've tried several times to install it, but it doesn't work

**Comment by NoTengoBattery** [comment]
Yes, I'm aware of it. I'm in the process of providing the packages myself. As you can understand, this is hard for me because I'm an individual with practically no resources (say, I have not a build bot nor a server to provide the packages).

However, in the next version I'm to upload today it will be available for installation without issue. Thank you for commenting this here, please stay tuned since I'll upload the next one soon.

**Comment by NoTengoBattery** [comment]
Please refer [here](https://github.com/NoTengoBattery/openwrt/releases/tag/v1.13.oc) and don't hesitate to provide any futher feedback.
