### ISSUE TITLE
WAN interface IPv4 DNS default configured to public IP instead of loopback

### ISSUE THREAD

**Issue by joshieecs** [NoTengoBattery/openwrt#8]
The default configuration sets the IPv4 WAN interface DNS server to **172**.0.0.1 rather than **127**.0.0.1. 

I don't think it functionally matters at all, because unbound is doing all the DNS work. A very minor issue, but it would probably be worth cleaning up the config file, because 172.0.0.1 is a public IP, and it should be very minor fix as well. 😊

In 2.02 the culprit is in `0014-custom-auto-configuation-boot-script.patch` line 271.

![jZOGFNnEA0](https://user-images.githubusercontent.com/3487932/99118086-7ad83080-25bc-11eb-8d1e-edf386dad2c6.png)
![0e28kuqogF](https://user-images.githubusercontent.com/3487932/99118089-7ca1f400-25bc-11eb-9970-8168cdf4e450.png)

**Comment by NoTengoBattery** [comment]
Nice catch!

It doesn't affect because it uses the IPv6 loopback address, but if you try to force (or for some reason, a program does not want to use IPv6) it, it will fail since the localhost is 127.x.x.x (all addresses work in Linux), but 172.0.0.1 is a globally routable address (i.e. the internet) and I think that the 172.0.0.1 router is not a DNS server. I'm gonna make it fixed for the next release, at this moment it can keep itself like it is.

ALSO: it may introduce delays in the IPv4 hosts and cause some of them to randomly fail. I think that this was the root cause of some users being unable to resolve names if they change DNS settings.

NOTE: the DNS shown inside the configuration only affects the DNS resolutions done from the device itself. All of the LAN clients will use the correct DNS server (i.e. unbound by default).
