### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by dzid26** [NoTengoBattery/openwrt#9]
Wouldn't it be better to put that long release descripton in Readme and only add short change descriptions with each release?
Thanks

**Comment by NoTengoBattery** [comment]
Hello, dear @dzid26
It would be nice to have that kind of change log in the releases, however, there is a small problem... or more than one, maybe, see:
1. Most of the visits to this repository (according to GitHub Insights) will land directly to the Releases page. This means that a big portion of the visitors, and by pure statistics, most of the new visitors, will never reach the `README.md` file and will get confused by the small details that they really want to find (like the `root` and WiFi password). For them, it's convenient to keep it in the releases.
1. Most links that lead directly to the Releases page are links that I can not control, they include links in the OpenWrt Wiki, links from other forks/projects that use this base code, links from Russian forums, internal links from business (don't ask me why my repo is visited from links from a business) but mainly the links that are indexed in search engines such as Google and DuckDuckGo.

Yes, I can squash most of the information and only provide new users with a quick start-up guide, and a link for further reading, but I think that it may not be as efficient for new users to find the information they are looking for. The idea of using the GitHub Releases itself was forcing the users to read through the document in the first place, but I catch your point.

Indeed, this Release notes (for version v2.05) is different from the others because I am working on refactoring it. There are many technical details that may not be worth including, especially for final users, so it can be compressed and developers can read through the commits and the patches to see the reasoning behind my decisions.
